//! Manages CLIProxyAPI as a child process within Presenter.
//!
//! CLIProxyAPI is a Go binary that provides an OpenAI-compatible API by
//! authenticating with Claude via OAuth. Presenter bundles it, manages
//! its lifecycle, and handles Claude OAuth authentication directly using
//! the PKCE flow with `platform.claude.com/oauth/code/callback`.

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use sha2::{Digest, Sha256};
use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::process::{Child, Command};
use tokio::sync::RwLock;
use tracing::{info, warn};

/// Default port for the embedded CLIProxyAPI instance.
const DEFAULT_PROXY_PORT: u16 = 18787;

/// Name of the CLIProxyAPI binary.
const PROXY_BINARY_NAME: &str = "cli-proxy-api";

/// Claude OAuth client ID (same one used by Claude Code / CLIProxyAPI).
const CLAUDE_CLIENT_ID: &str = "9d1c250a-e61b-44d9-88ed-5944d1962f5e";

/// Redirect URI that shows the code on a Claude page for the user to copy.
const CLAUDE_REDIRECT_URI: &str = "https://platform.claude.com/oauth/code/callback";

/// Claude OAuth token exchange endpoint.
const CLAUDE_TOKEN_ENDPOINT: &str = "https://platform.claude.com/v1/oauth/token";

/// State of the managed CLIProxyAPI process.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyStatus {
    pub running: bool,
    pub port: u16,
    pub api_url: String,
    pub binary_found: bool,
    pub claude_authenticated: bool,
}

/// Configuration for the embedded proxy.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyConfig {
    #[serde(default = "default_proxy_port")]
    pub port: u16,
    #[serde(default = "default_true")]
    pub auto_start: bool,
}

fn default_proxy_port() -> u16 {
    DEFAULT_PROXY_PORT
}

fn default_true() -> bool {
    true
}

impl Default for ProxyConfig {
    fn default() -> Self {
        Self {
            port: DEFAULT_PROXY_PORT,
            auto_start: true,
        }
    }
}

/// PKCE state stored between the auth URL generation and code exchange.
struct PkceState {
    code_verifier: String,
    #[allow(dead_code)]
    state: String,
}

/// Manages the CLIProxyAPI child process and Claude OAuth.
pub struct ProxyManager {
    child: Arc<RwLock<Option<Child>>>,
    pkce_state: Arc<RwLock<Option<PkceState>>>,
    config: Arc<RwLock<ProxyConfig>>,
    deploy_dir: PathBuf,
}

impl ProxyManager {
    pub fn new(deploy_dir: PathBuf) -> Self {
        Self {
            child: Arc::new(RwLock::new(None)),
            pkce_state: Arc::new(RwLock::new(None)),
            config: Arc::new(RwLock::new(ProxyConfig::default())),
            deploy_dir,
        }
    }

    fn binary_path(&self) -> Option<PathBuf> {
        let deploy_path = self.deploy_dir.join(PROXY_BINARY_NAME);
        if deploy_path.exists() {
            return Some(deploy_path);
        }

        let cwd_path = PathBuf::from(PROXY_BINARY_NAME);
        if cwd_path.exists() {
            return Some(cwd_path);
        }

        if let Ok(output) = std::process::Command::new("which")
            .arg(PROXY_BINARY_NAME)
            .output()
        {
            if output.status.success() {
                let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
                if !path.is_empty() {
                    return Some(PathBuf::from(path));
                }
            }
        }

        None
    }

    fn auth_dir(&self) -> PathBuf {
        self.deploy_dir.join(".cli-proxy-api")
    }

    fn config_path(&self) -> PathBuf {
        self.deploy_dir.join("cli-proxy-api-config.yaml")
    }

    /// Check if Claude credentials exist (either OAuth tokens or API key in config).
    pub fn is_claude_authenticated(&self) -> bool {
        // Check for claude-api-key in config
        if let Ok(content) = std::fs::read_to_string(self.config_path()) {
            if content.contains("claude-api-key:") {
                return true;
            }
        }
        // Check for token files in auth dir
        let auth_dir = self.auth_dir();
        auth_dir.exists()
            && std::fs::read_dir(&auth_dir)
                .map(|entries| {
                    entries
                        .filter_map(|e| e.ok())
                        .any(|e| e.file_name().to_string_lossy().contains("claude"))
                })
                .unwrap_or(false)
    }

    /// Write the config YAML file for CLIProxyAPI.
    async fn write_config_with_key(&self, api_key: Option<&str>) -> anyhow::Result<()> {
        let config = self.config.read().await;
        let auth_dir = self.auth_dir();

        let key_section = if let Some(key) = api_key {
            format!(
                r#"
claude-api-key:
  - api-key: "{key}"
"#
            )
        } else {
            String::new()
        };

        let config_content = format!(
            r#"# Auto-generated by Presenter - do not edit
host: "127.0.0.1"
port: {port}
auth-dir: "{auth_dir}"
debug: false
logging-to-file: false
request-retry: 2
{key_section}"#,
            port = config.port,
            auth_dir = auth_dir.display(),
        );

        tokio::fs::create_dir_all(&auth_dir).await?;
        tokio::fs::write(self.config_path(), config_content).await?;
        Ok(())
    }

    /// Start the CLIProxyAPI process.
    pub async fn start(&self) -> anyhow::Result<()> {
        {
            let guard = self.child.read().await;
            if guard.is_some() {
                return Ok(());
            }
        }

        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        // Write config preserving any existing API key
        let existing_key = self.read_existing_api_key().await;
        self.write_config_with_key(existing_key.as_deref()).await?;

        let config = self.config.read().await;
        info!(binary = %binary.display(), port = config.port, "starting CLIProxyAPI");

        let child = Command::new(&binary)
            .arg("-config")
            .arg(self.config_path())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .kill_on_drop(true)
            .spawn()?;

        {
            let mut guard = self.child.write().await;
            *guard = Some(child);
        }

        tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;

        let port = config.port;
        drop(config);
        let url = format!("http://127.0.0.1:{port}/v1/models");
        match reqwest::Client::new()
            .get(&url)
            .timeout(std::time::Duration::from_secs(5))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                info!(port, "CLIProxyAPI started successfully");
            }
            Ok(resp) => {
                warn!(port, status = %resp.status(), "CLIProxyAPI responded with non-success");
            }
            Err(e) => {
                warn!(?e, "CLIProxyAPI may not have started correctly");
            }
        }
        Ok(())
    }

    /// Stop the CLIProxyAPI process.
    pub async fn stop(&self) -> anyhow::Result<()> {
        let mut guard = self.child.write().await;
        if let Some(mut child) = guard.take() {
            info!("stopping CLIProxyAPI");
            child.kill().await.ok();
            child.wait().await.ok();
        }
        Ok(())
    }

    /// Restart the process.
    pub async fn restart(&self) -> anyhow::Result<()> {
        self.stop().await?;
        self.start().await
    }

    /// Get current status.
    pub async fn status(&self) -> ProxyStatus {
        let config = self.config.read().await;
        let port = config.port;
        drop(config);

        ProxyStatus {
            running: self.is_running().await,
            port,
            api_url: format!("http://127.0.0.1:{port}/v1"),
            binary_found: self.binary_path().is_some(),
            claude_authenticated: self.is_claude_authenticated(),
        }
    }

    async fn is_running(&self) -> bool {
        let mut guard = self.child.write().await;
        if let Some(ref mut child) = *guard {
            match child.try_wait() {
                Ok(None) => true,
                _ => {
                    *guard = None;
                    false
                }
            }
        } else {
            false
        }
    }

    // ── OAuth PKCE Flow ──

    /// Generate the Claude OAuth authorization URL using PKCE.
    ///
    /// Returns a URL the user opens in their browser. After authorizing,
    /// Claude shows the authorization code on `platform.claude.com` for
    /// the user to copy and paste back into Presenter.
    pub async fn generate_oauth_url(&self) -> anyhow::Result<String> {
        let code_verifier = generate_code_verifier();
        let code_challenge = generate_code_challenge(&code_verifier);
        let state = generate_state();

        let url = format!(
            "https://claude.ai/oauth/authorize\
             ?code=true\
             &client_id={CLAUDE_CLIENT_ID}\
             &response_type=code\
             &redirect_uri={redirect}\
             &scope={scope}\
             &code_challenge={code_challenge}\
             &code_challenge_method=S256\
             &state={state}",
            redirect = urlencod(CLAUDE_REDIRECT_URI),
            scope = urlencod("org:create_api_key user:profile user:inference"),
        );

        // Store PKCE state for the exchange step
        {
            let mut guard = self.pkce_state.write().await;
            *guard = Some(PkceState {
                code_verifier,
                state,
            });
        }

        info!("generated Claude OAuth URL");
        Ok(url)
    }

    /// Exchange an authorization code for an API key/token.
    ///
    /// The user copies the code from `platform.claude.com/oauth/code/callback`
    /// and pastes it into Presenter. This method exchanges it at Anthropic's
    /// token endpoint using the stored PKCE code_verifier.
    pub async fn exchange_code(&self, raw_code: &str) -> anyhow::Result<String> {
        // Strip hash fragment if present (e.g. "code_value#state_hash")
        let code = raw_code.split('#').next().unwrap_or(raw_code).trim();

        let code_verifier = {
            let guard = self.pkce_state.read().await;
            guard
                .as_ref()
                .map(|s| s.code_verifier.clone())
                .ok_or_else(|| {
                    anyhow::anyhow!("no pending OAuth flow — click 'Claude Login' first")
                })?
        };

        let form_body = format!(
            "grant_type=authorization_code&client_id={}&code={}&code_verifier={}&redirect_uri={}",
            CLAUDE_CLIENT_ID,
            code,
            code_verifier,
            "https%3A%2F%2Fplatform.claude.com%2Foauth%2Fcode%2Fcallback"
        );

        info!(
            url = CLAUDE_TOKEN_ENDPOINT,
            body_len = form_body.len(),
            code_len = code.len(),
            verifier_len = code_verifier.len(),
            "exchanging OAuth code for token"
        );

        let resp = reqwest::Client::new()
            .post(CLAUDE_TOKEN_ENDPOINT)
            .header("Content-Type", "application/x-www-form-urlencoded")
            .body(form_body)
            .timeout(std::time::Duration::from_secs(15))
            .send()
            .await?;

        if !resp.status().is_success() {
            let status = resp.status();
            let text = resp.text().await.unwrap_or_default();
            anyhow::bail!("token exchange failed (HTTP {status}): {text}");
        }

        let json: serde_json::Value = resp.json().await?;
        let token = json["access_token"]
            .as_str()
            .ok_or_else(|| anyhow::anyhow!("no access_token in response: {json}"))?;

        // Clear PKCE state
        {
            let mut guard = self.pkce_state.write().await;
            *guard = None;
        }

        info!("OAuth token exchange successful");
        Ok(token.to_string())
    }

    /// Store a Claude API key in the CLIProxyAPI config and restart the proxy.
    pub async fn store_token_and_restart(&self, token: &str) -> anyhow::Result<()> {
        info!("storing Claude token in CLIProxyAPI config");
        self.write_config_with_key(Some(token)).await?;

        if self.is_running().await {
            self.restart().await?;
        } else {
            self.start().await?;
        }

        Ok(())
    }

    /// Read existing API key from config file (if any).
    async fn read_existing_api_key(&self) -> Option<String> {
        let content = tokio::fs::read_to_string(self.config_path()).await.ok()?;
        // Simple extraction: look for api-key: "..." line
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("- api-key:") || trimmed.starts_with("api-key:") {
                let value = trimmed.split(':').nth(1)?.trim().trim_matches('"').trim();
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
        None
    }

    /// Auto-start if configured and binary exists.
    pub async fn auto_start(&self) {
        let config = self.config.read().await;
        let should_start = config.auto_start;
        drop(config);

        if should_start && self.binary_path().is_some() {
            if let Err(e) = self.start().await {
                warn!(?e, "failed to auto-start CLIProxyAPI");
            }
        }
    }
}

// ── PKCE Helpers ──

/// Generate a random code_verifier (43-128 URL-safe characters).
fn generate_code_verifier() -> String {
    use rand::Rng;
    const CHARSET: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~";
    let mut rng = rand::rng();
    (0..64)
        .map(|_| {
            let idx = rng.random_range(0..CHARSET.len());
            CHARSET[idx] as char
        })
        .collect()
}

/// Generate code_challenge = BASE64URL_NO_PAD(SHA256(code_verifier)).
fn generate_code_challenge(code_verifier: &str) -> String {
    let hash = Sha256::digest(code_verifier.as_bytes());
    URL_SAFE_NO_PAD.encode(hash)
}

/// Generate a random state parameter (32 hex chars).
fn generate_state() -> String {
    use rand::Rng;
    let mut rng = rand::rng();
    let bytes: [u8; 16] = rng.random();
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Percent-encode a string for use in a URL query parameter.
fn urlencod(s: &str) -> String {
    s.replace(':', "%3A").replace('/', "%2F").replace(' ', "+")
}

/// Determine the deploy directory (where presenter-server lives).
pub fn detect_deploy_dir() -> PathBuf {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."))
}
