//! Manages CLIProxyAPI as a child process within Presenter.
//!
//! CLIProxyAPI is a Go binary that provides an OpenAI-compatible API by
//! authenticating with Claude via OAuth. Presenter bundles it, manages
//! its lifecycle, and delegates Claude OAuth login to CLIProxyAPI's
//! native `-claude-login` flow (accessed via SSH tunnel).

use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::io::AsyncBufReadExt;
use tokio::process::{Child, Command};
use tokio::sync::RwLock;
use tracing::{info, warn};

/// Default port for the embedded CLIProxyAPI instance.
const DEFAULT_PROXY_PORT: u16 = 18787;

/// Name of the CLIProxyAPI binary.
const PROXY_BINARY_NAME: &str = "cli-proxy-api";

/// State of the managed CLIProxyAPI process.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyStatus {
    pub running: bool,
    pub port: u16,
    pub api_url: String,
    pub binary_found: bool,
    pub claude_authenticated: bool,
}

/// Configuration for the embedded proxy.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyConfig {
    #[serde(default = "default_proxy_port")]
    pub port: u16,
    #[serde(default = "default_true")]
    pub auto_start: bool,
}

fn default_proxy_port() -> u16 {
    DEFAULT_PROXY_PORT
}

fn default_true() -> bool {
    true
}

impl Default for ProxyConfig {
    fn default() -> Self {
        Self {
            port: DEFAULT_PROXY_PORT,
            auto_start: true,
        }
    }
}

/// Manages the CLIProxyAPI child process and Claude OAuth.
pub struct ProxyManager {
    child: Arc<RwLock<Option<Child>>>,
    login_child: Arc<RwLock<Option<Child>>>,
    config: Arc<RwLock<ProxyConfig>>,
    deploy_dir: PathBuf,
}

impl ProxyManager {
    pub fn new(deploy_dir: PathBuf) -> Self {
        Self {
            child: Arc::new(RwLock::new(None)),
            login_child: Arc::new(RwLock::new(None)),
            config: Arc::new(RwLock::new(ProxyConfig::default())),
            deploy_dir,
        }
    }

    fn binary_path(&self) -> Option<PathBuf> {
        let deploy_path = self.deploy_dir.join(PROXY_BINARY_NAME);
        if deploy_path.exists() {
            return Some(deploy_path);
        }

        let cwd_path = PathBuf::from(PROXY_BINARY_NAME);
        if cwd_path.exists() {
            return Some(cwd_path);
        }

        if let Ok(output) = std::process::Command::new("which")
            .arg(PROXY_BINARY_NAME)
            .output()
        {
            if output.status.success() {
                let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
                if !path.is_empty() {
                    return Some(PathBuf::from(path));
                }
            }
        }

        None
    }

    fn auth_dir(&self) -> PathBuf {
        self.deploy_dir.join(".cli-proxy-api")
    }

    fn config_path(&self) -> PathBuf {
        self.deploy_dir.join("cli-proxy-api-config.yaml")
    }

    /// Check if Claude credentials exist (either OAuth tokens or API key in config).
    pub fn is_claude_authenticated(&self) -> bool {
        // Check for claude-api-key in config
        if let Ok(content) = std::fs::read_to_string(self.config_path()) {
            if content.contains("claude-api-key:") {
                return true;
            }
        }
        // Check for token files in auth dir
        let auth_dir = self.auth_dir();
        auth_dir.exists()
            && std::fs::read_dir(&auth_dir)
                .map(|entries| {
                    entries
                        .filter_map(|e| e.ok())
                        .any(|e| e.file_name().to_string_lossy().contains("claude"))
                })
                .unwrap_or(false)
    }

    /// Write the config YAML file for CLIProxyAPI.
    async fn write_config_with_key(&self, api_key: Option<&str>) -> anyhow::Result<()> {
        let config = self.config.read().await;
        let auth_dir = self.auth_dir();

        let key_section = if let Some(key) = api_key {
            format!(
                r#"
claude-api-key:
  - api-key: "{key}"
"#
            )
        } else {
            String::new()
        };

        let config_content = format!(
            r#"# Auto-generated by Presenter - do not edit
host: "127.0.0.1"
port: {port}
auth-dir: "{auth_dir}"
debug: false
logging-to-file: false
request-retry: 2
{key_section}"#,
            port = config.port,
            auth_dir = auth_dir.display(),
        );

        tokio::fs::create_dir_all(&auth_dir).await?;
        tokio::fs::write(self.config_path(), config_content).await?;
        Ok(())
    }

    /// Start the CLIProxyAPI process.
    pub async fn start(&self) -> anyhow::Result<()> {
        {
            let guard = self.child.read().await;
            if guard.is_some() {
                return Ok(());
            }
        }

        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        // Write config preserving any existing API key
        let existing_key = self.read_existing_api_key().await;
        self.write_config_with_key(existing_key.as_deref()).await?;

        let config = self.config.read().await;
        info!(binary = %binary.display(), port = config.port, "starting CLIProxyAPI");

        let child = Command::new(&binary)
            .arg("-config")
            .arg(self.config_path())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::null())
            .kill_on_drop(true)
            .spawn()?;

        {
            let mut guard = self.child.write().await;
            *guard = Some(child);
        }

        tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;

        let port = config.port;
        drop(config);
        let url = format!("http://127.0.0.1:{port}/v1/models");
        match reqwest::Client::new()
            .get(&url)
            .timeout(std::time::Duration::from_secs(5))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                info!(port, "CLIProxyAPI started successfully");
            }
            Ok(resp) => {
                warn!(port, status = %resp.status(), "CLIProxyAPI responded with non-success");
            }
            Err(e) => {
                warn!(?e, "CLIProxyAPI may not have started correctly");
            }
        }
        Ok(())
    }

    /// Stop the CLIProxyAPI process.
    pub async fn stop(&self) -> anyhow::Result<()> {
        let mut guard = self.child.write().await;
        if let Some(mut child) = guard.take() {
            info!("stopping CLIProxyAPI");
            child.kill().await.ok();
            child.wait().await.ok();
        }
        Ok(())
    }

    /// Get current status.
    pub async fn status(&self) -> ProxyStatus {
        let config = self.config.read().await;
        let port = config.port;
        drop(config);

        ProxyStatus {
            running: self.is_running().await,
            port,
            api_url: format!("http://127.0.0.1:{port}/v1"),
            binary_found: self.binary_path().is_some(),
            claude_authenticated: self.is_claude_authenticated(),
        }
    }

    async fn is_running(&self) -> bool {
        let mut guard = self.child.write().await;
        if let Some(ref mut child) = *guard {
            match child.try_wait() {
                Ok(None) => true,
                _ => {
                    *guard = None;
                    false
                }
            }
        } else {
            false
        }
    }

    // ── Claude Login via CLIProxyAPI ──

    /// Spawn `cli-proxy-api -claude-login -no-browser` and read the auth URL
    /// from its stdout. The login process listens on port 54545 for the OAuth
    /// callback — the user establishes an SSH tunnel to reach it.
    ///
    /// Returns the authorization URL the user should open in their browser.
    pub async fn claude_login(&self) -> anyhow::Result<String> {
        // Kill any previous login process
        {
            let mut guard = self.login_child.write().await;
            if let Some(mut child) = guard.take() {
                child.kill().await.ok();
                child.wait().await.ok();
            }
        }

        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        // Ensure config exists so -config flag works
        let existing_key = self.read_existing_api_key().await;
        self.write_config_with_key(existing_key.as_deref()).await?;

        info!(binary = %binary.display(), "starting CLIProxyAPI claude-login");

        let mut child = Command::new(&binary)
            .arg("-claude-login")
            .arg("-no-browser")
            .arg("-config")
            .arg(self.config_path())
            .stdout(std::process::Stdio::piped())
            .stderr(std::process::Stdio::piped())
            .kill_on_drop(true)
            .spawn()?;

        // Read stdout lines looking for the auth URL
        let stdout = child
            .stdout
            .take()
            .ok_or_else(|| anyhow::anyhow!("failed to capture login process stdout"))?;

        let mut reader = tokio::io::BufReader::new(stdout).lines();
        let mut auth_url: Option<String> = None;

        // Give the process up to 10 seconds to print the URL
        let deadline = tokio::time::Instant::now() + tokio::time::Duration::from_secs(10);
        loop {
            let remaining = deadline.saturating_duration_since(tokio::time::Instant::now());
            if remaining.is_zero() {
                break;
            }

            match tokio::time::timeout(remaining, reader.next_line()).await {
                Ok(Ok(Some(line))) => {
                    info!(line = %line, "claude-login stdout");
                    // Look for a line containing an https URL
                    if let Some(url_start) = line.find("https://") {
                        let url = line[url_start..].split_whitespace().next().unwrap_or("");
                        if !url.is_empty() {
                            auth_url = Some(url.to_string());
                            break;
                        }
                    }
                }
                Ok(Ok(None)) => break, // EOF
                Ok(Err(e)) => {
                    warn!(?e, "error reading claude-login stdout");
                    break;
                }
                Err(_) => break, // timeout
            }
        }

        let url = auth_url.ok_or_else(|| {
            anyhow::anyhow!("claude-login did not produce an auth URL within 10s")
        })?;

        // Keep the login child alive — it needs to receive the OAuth callback
        {
            let mut guard = self.login_child.write().await;
            *guard = Some(child);
        }

        info!("claude-login URL obtained, waiting for OAuth callback via SSH tunnel");
        Ok(url)
    }

    /// Read existing API key from config file (if any).
    async fn read_existing_api_key(&self) -> Option<String> {
        let content = tokio::fs::read_to_string(self.config_path()).await.ok()?;
        // Simple extraction: look for api-key: "..." line
        for line in content.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("- api-key:") || trimmed.starts_with("api-key:") {
                let value = trimmed.split(':').nth(1)?.trim().trim_matches('"').trim();
                if !value.is_empty() {
                    return Some(value.to_string());
                }
            }
        }
        None
    }

    /// Auto-start if configured and binary exists.
    pub async fn auto_start(&self) {
        let config = self.config.read().await;
        let should_start = config.auto_start;
        drop(config);

        if should_start && self.binary_path().is_some() {
            if let Err(e) = self.start().await {
                warn!(?e, "failed to auto-start CLIProxyAPI");
            }
        }
    }
}

/// Determine the deploy directory (where presenter-server lives).
pub fn detect_deploy_dir() -> PathBuf {
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."))
}
