//! Manages CLIProxyAPI as a child process within Presenter.
//!
//! CLIProxyAPI is a Go binary that provides an OpenAI-compatible API by
//! authenticating with Claude via OAuth. Presenter bundles it and manages
//! its lifecycle automatically.

use std::path::{Path, PathBuf};
use std::sync::Arc;
use tokio::process::{Child, Command};
use tokio::sync::RwLock;
use tracing::{info, warn};

/// Default port for the embedded CLIProxyAPI instance.
const DEFAULT_PROXY_PORT: u16 = 18787;

/// Name of the CLIProxyAPI binary.
const PROXY_BINARY_NAME: &str = "cli-proxy-api";

/// State of the managed CLIProxyAPI process.
#[derive(Debug, Clone, serde::Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyStatus {
    pub running: bool,
    pub port: u16,
    pub api_url: String,
    pub binary_found: bool,
    pub claude_authenticated: bool,
}

/// Configuration for the embedded proxy.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProxyConfig {
    #[serde(default = "default_proxy_port")]
    pub port: u16,
    #[serde(default = "default_true")]
    pub auto_start: bool,
}

fn default_proxy_port() -> u16 {
    DEFAULT_PROXY_PORT
}

fn default_true() -> bool {
    true
}

impl Default for ProxyConfig {
    fn default() -> Self {
        Self {
            port: DEFAULT_PROXY_PORT,
            auto_start: true,
        }
    }
}

/// Manages the CLIProxyAPI child process.
pub struct ProxyManager {
    child: Arc<RwLock<Option<Child>>>,
    config: Arc<RwLock<ProxyConfig>>,
    deploy_dir: PathBuf,
}

impl ProxyManager {
    pub fn new(deploy_dir: PathBuf) -> Self {
        Self {
            child: Arc::new(RwLock::new(None)),
            config: Arc::new(RwLock::new(ProxyConfig::default())),
            deploy_dir,
        }
    }

    /// Resolve the binary path. Searches:
    /// 1. Same directory as presenter-server (deploy dir)
    /// 2. Working directory
    /// 3. PATH
    fn binary_path(&self) -> Option<PathBuf> {
        // Check deploy directory
        let deploy_path = self.deploy_dir.join(PROXY_BINARY_NAME);
        if deploy_path.exists() {
            return Some(deploy_path);
        }

        // Check working directory
        let cwd_path = PathBuf::from(PROXY_BINARY_NAME);
        if cwd_path.exists() {
            return Some(cwd_path);
        }

        // Check if in PATH
        if let Ok(output) = std::process::Command::new("which")
            .arg(PROXY_BINARY_NAME)
            .output()
        {
            if output.status.success() {
                let path = String::from_utf8_lossy(&output.stdout).trim().to_string();
                if !path.is_empty() {
                    return Some(PathBuf::from(path));
                }
            }
        }

        None
    }

    /// Auth directory where CLIProxyAPI stores OAuth tokens.
    fn auth_dir(&self) -> PathBuf {
        self.deploy_dir.join(".cli-proxy-api")
    }

    /// Config file path for the managed instance.
    fn config_path(&self) -> PathBuf {
        self.deploy_dir.join("cli-proxy-api-config.yaml")
    }

    /// Check if Claude OAuth tokens exist (authentication has been done).
    pub fn is_claude_authenticated(&self) -> bool {
        let auth_dir = self.auth_dir();
        // CLIProxyAPI stores tokens in the auth directory
        auth_dir.exists()
            && std::fs::read_dir(&auth_dir)
                .map(|entries| {
                    entries
                        .filter_map(|e| e.ok())
                        .any(|e| e.file_name().to_string_lossy().contains("claude"))
                })
                .unwrap_or(false)
    }

    /// Write the config YAML file for CLIProxyAPI.
    async fn write_config(&self) -> anyhow::Result<()> {
        let config = self.config.read().await;
        let auth_dir = self.auth_dir();
        let config_content = format!(
            r#"# Auto-generated by Presenter - do not edit
host: "127.0.0.1"
port: {port}
auth-dir: "{auth_dir}"
debug: false
logging-to-file: false
request-retry: 2
"#,
            port = config.port,
            auth_dir = auth_dir.display(),
        );

        tokio::fs::create_dir_all(&auth_dir).await?;
        tokio::fs::write(self.config_path(), config_content).await?;
        Ok(())
    }

    /// Start the CLIProxyAPI process.
    pub async fn start(&self) -> anyhow::Result<()> {
        // Check if already running
        {
            let guard = self.child.read().await;
            if guard.is_some() {
                return Ok(());
            }
        }

        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        self.write_config().await?;

        let config = self.config.read().await;
        info!(
            binary = %binary.display(),
            port = config.port,
            "starting CLIProxyAPI"
        );

        let child = Command::new(&binary)
            .arg("-config")
            .arg(self.config_path())
            .stdout(std::process::Stdio::null())
            .stderr(std::process::Stdio::piped())
            .kill_on_drop(true)
            .spawn()?;

        {
            let mut guard = self.child.write().await;
            *guard = Some(child);
        }

        // Wait briefly for it to start
        tokio::time::sleep(tokio::time::Duration::from_secs(2)).await;

        // Verify it's responding
        let port = config.port;
        drop(config);
        let url = format!("http://127.0.0.1:{port}/v1/models");
        match reqwest::Client::new()
            .get(&url)
            .timeout(std::time::Duration::from_secs(5))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                info!(port, "CLIProxyAPI started successfully");
                Ok(())
            }
            Ok(resp) => {
                warn!(
                    port,
                    status = %resp.status(),
                    "CLIProxyAPI started but returned non-success"
                );
                Ok(()) // Still running, might just need auth
            }
            Err(e) => {
                warn!(?e, "CLIProxyAPI may not have started correctly");
                Ok(()) // Don't fail — it might be slow to start
            }
        }
    }

    /// Stop the CLIProxyAPI process.
    pub async fn stop(&self) -> anyhow::Result<()> {
        let mut guard = self.child.write().await;
        if let Some(mut child) = guard.take() {
            info!("stopping CLIProxyAPI");
            child.kill().await.ok();
            child.wait().await.ok();
        }
        Ok(())
    }

    /// Restart the process.
    #[allow(dead_code)]
    pub async fn restart(&self) -> anyhow::Result<()> {
        self.stop().await?;
        self.start().await
    }

    /// Get current status.
    pub async fn status(&self) -> ProxyStatus {
        let config = self.config.read().await;
        let port = config.port;
        drop(config);

        let binary_found = self.binary_path().is_some();
        let running = self.is_running().await;
        let claude_authenticated = self.is_claude_authenticated();

        ProxyStatus {
            running,
            port,
            api_url: format!("http://127.0.0.1:{port}/v1"),
            binary_found,
            claude_authenticated,
        }
    }

    /// Check if the process is still alive.
    async fn is_running(&self) -> bool {
        let mut guard = self.child.write().await;
        if let Some(ref mut child) = *guard {
            // try_wait returns None if still running
            match child.try_wait() {
                Ok(None) => true,
                Ok(Some(_)) => {
                    *guard = None; // Process exited, clean up
                    false
                }
                Err(_) => {
                    *guard = None;
                    false
                }
            }
        } else {
            false
        }
    }

    /// Run the Claude OAuth login flow. Returns the login URL for the user.
    pub async fn claude_login(&self) -> anyhow::Result<String> {
        let binary = self
            .binary_path()
            .ok_or_else(|| anyhow::anyhow!("CLIProxyAPI binary not found"))?;

        // Ensure auth dir exists
        let auth_dir = self.auth_dir();
        tokio::fs::create_dir_all(&auth_dir).await?;

        // Run login with --no-browser to get the URL
        let output = Command::new(&binary)
            .arg("-claude-login")
            .arg("-no-browser")
            .arg("-config")
            .arg(self.config_path())
            .output()
            .await?;

        let stderr = String::from_utf8_lossy(&output.stderr);
        let stdout = String::from_utf8_lossy(&output.stdout);
        let combined = format!("{stdout}\n{stderr}");

        // Extract URL from output
        for line in combined.lines() {
            let trimmed = line.trim();
            if trimmed.starts_with("http://") || trimmed.starts_with("https://") {
                return Ok(trimmed.to_string());
            }
        }

        // If no URL found, return the full output for debugging
        anyhow::bail!("Could not extract login URL. Output: {combined}")
    }

    /// Update the proxy configuration.
    #[allow(dead_code)]
    pub async fn update_config(&self, new_config: ProxyConfig) -> anyhow::Result<()> {
        let was_running = self.is_running().await;
        {
            let mut guard = self.config.write().await;
            *guard = new_config;
        }
        if was_running {
            self.restart().await?;
        }
        Ok(())
    }

    /// Get the API URL for this proxy instance.
    #[allow(dead_code)]
    pub async fn api_url(&self) -> String {
        let config = self.config.read().await;
        format!("http://127.0.0.1:{}/v1", config.port)
    }

    /// Auto-start if configured and binary exists.
    pub async fn auto_start(&self) {
        let config = self.config.read().await;
        let should_start = config.auto_start;
        drop(config);

        if should_start && self.binary_path().is_some() {
            if let Err(e) = self.start().await {
                warn!(?e, "failed to auto-start CLIProxyAPI");
            }
        }
    }
}

/// Determine the deploy directory (where presenter-server lives).
pub fn detect_deploy_dir() -> PathBuf {
    // Use the directory of the current executable
    std::env::current_exe()
        .ok()
        .and_then(|p| p.parent().map(Path::to_path_buf))
        .unwrap_or_else(|| PathBuf::from("."))
}
