import { test, expect, type Page, type Route } from "@playwright/test";
import {
  attachConsoleErrorCollector,
  deriveTestConfig,
  refreshDevData,
  startTestServer,
  stopServer,
  type ServerHandle,
} from "./support";

// ─────────────────────────────────────────────────────────────────────────
// #670 — `install_pagehide_teardown()` (ndi_video.rs) is called on EVERY
// successful WHEP connect inside the reconnect loop's
// `Ok(ConnectOutcome::Connected(_))` arm — not just the FIRST connect a
// <NdiVideo> mount ever makes. It used to `.forget()`-leak its `window`
// `pagehide` listener under the false doc-commented assumption that the
// function runs (at most) once per mount; in fact a long-running stage
// display that reconnects over hours/days accumulated one MORE permanent
// `pagehide` listener per reconnect, forever.
//
// This CI runner has no NDI SDK, so `/ndi/whep/<id>` always answers 503/204
// and `connect_whep()` never reaches `Ok(Connected(_))` for real (the same
// reason ndi-webrtc-recovery.spec.ts skips itself on this lane). To exercise
// the REAL Connected/reconnect code path deterministically without NDI
// hardware, this test intercepts the WHEP POST (`page.route`) and answers it
// with a genuine SDP answer generated by an EPHEMERAL `RTCPeerConnection`
// created inside the page — a real Chrome-negotiated answer, so
// `set_remote_description` genuinely succeeds and
// `Ok(ConnectOutcome::Connected(_))` fires for real. A reconnect is then
// forced DETERMINISTICALLY (never wait on real ICE-failure timing, which is
// unbounded and would be flaky): the test captures the `RTCPeerConnection`
// Rust registers `oniceconnectionstatechange` on, forces its
// `iceConnectionState` getter to report "failed", and dispatches a real
// `iceconnectionstatechange` Event — invoking the SAME
// `install_ice_failure_listener` handler (ndi_watchdog.rs) a genuine ICE
// failure would.
//
// Same instrumentation SHAPE as the #637 test in
// stage-ndi-playback-guard.spec.ts: `EventTarget.prototype`
// add/removeEventListener patched via `page.addInitScript`, the net
// (adds - removes) count for "pagehide" tracked, and asserted to stay
// bounded (never grow) across N reconnect cycles, then return to 0 on
// unmount.
// ─────────────────────────────────────────────────────────────────────────

test.describe.configure({ timeout: 180_000 });

let server: ServerHandle | undefined;
let baseURL = "";
let dbUrl = "";
let port = 0;

test.beforeAll(async ({}, testInfo) => {
  const cfg = deriveTestConfig(testInfo);
  baseURL = cfg.baseURL;
  dbUrl = cfg.dbUrl;
  port = cfg.port;
  await refreshDevData(dbUrl);
  server = await startTestServer(port, dbUrl, cfg.oscPort);
});

test.afterAll(async () => {
  await stopServer(server);
  server = undefined;
});

/** Console noise this test deliberately produces by injecting a fake ICE
 * failure (the whole point of `forceIceFailure` below) — never a symptom of
 * something actually broken. */
const ALLOWED_CONSOLE_NOISE = [/watchdog: ICE state=Failed, triggering reconnect/i];

/** Instrument (before the WASM bundle boots) the net "pagehide" listener
 * count on `window` AND capture every `RTCPeerConnection` Rust registers
 * `oniceconnectionstatechange` on — the two pieces of test-only DOM state
 * `pagehideNet()`/`forceIceFailure()` below read/drive. */
async function installIceAndPagehideInstrumentation(page: Page): Promise<void> {
  await page.addInitScript(() => {
    // Net add/remove count for "pagehide" — same instrumentation shape as
    // the #637 `EventTarget.prototype` patch in
    // stage-ndi-playback-guard.spec.ts.
    const proto = EventTarget.prototype;
    const originalAdd = proto.addEventListener;
    const originalRemove = proto.removeEventListener;
    let net = 0;
    (window as unknown as { __e2ePagehideNet: () => number }).__e2ePagehideNet = () => net;
    proto.addEventListener = function (
      this: EventTarget,
      type: string,
      listener: EventListenerOrEventListenerObject | null,
      options?: boolean | AddEventListenerOptions,
    ) {
      if (type === "pagehide") net += 1;
      return originalAdd.call(this, type, listener, options);
    };
    proto.removeEventListener = function (
      this: EventTarget,
      type: string,
      listener: EventListenerOrEventListenerObject | null,
      options?: boolean | EventListenerOptions,
    ) {
      if (type === "pagehide") net -= 1;
      return originalRemove.call(this, type, listener, options);
    };

    // Capture every `pc` Rust assigns `.oniceconnectionstatechange` on
    // (`Watchdog::install` -> `install_ice_failure_listener`, ndi_watchdog.rs)
    // so the test can force a DETERMINISTIC "ICE failed" event on the exact
    // RTCPeerConnection the reconnect loop is currently watching, instead of
    // waiting on real (unbounded, flaky) ICE negotiation timing.
    const pcs: RTCPeerConnection[] = [];
    (window as unknown as { __e2eIcePcs: RTCPeerConnection[] }).__e2eIcePcs = pcs;
    // Defensive: walk the prototype chain for the descriptor rather than
    // assuming it lives directly on RTCPeerConnection.prototype. If it's
    // genuinely not found anywhere, skip the patch rather than throwing
    // during WASM bootstrap (addInitScript exceptions there are fatal to
    // the whole page) — forceIceFailure() would then fail loudly with an
    // empty `pcs` array instead, isolated to this test's own assertions.
    let rtcProto: object | null = RTCPeerConnection.prototype;
    let iceDesc: PropertyDescriptor | undefined;
    while (rtcProto && !iceDesc) {
      iceDesc = Object.getOwnPropertyDescriptor(rtcProto, "oniceconnectionstatechange");
      rtcProto = Object.getPrototypeOf(rtcProto);
    }
    if (iceDesc?.get && iceDesc.set) {
      const originalGet = iceDesc.get;
      const originalSet = iceDesc.set;
      Object.defineProperty(RTCPeerConnection.prototype, "oniceconnectionstatechange", {
        configurable: true,
        get(this: RTCPeerConnection) {
          return originalGet.call(this);
        },
        set(this: RTCPeerConnection, handler: unknown) {
          pcs.push(this);
          originalSet.call(this, handler);
        },
      });
    }
  });
}

/** Current net "pagehide" listener count on `window`. */
function pagehideNet(page: Page): Promise<number> {
  return page.evaluate(
    () => (window as unknown as { __e2ePagehideNet: () => number }).__e2ePagehideNet(),
  );
}

/** Force the LATEST RTCPeerConnection the reconnect loop is watching into a
 * synthetic "failed" ICE state and fire the real event — deterministically
 * triggering `install_ice_failure_listener`'s reconnect without waiting on
 * real (unbounded) ICE negotiation timing. */
async function forceIceFailure(page: Page): Promise<void> {
  await page.evaluate(() => {
    const pcs = (window as unknown as { __e2eIcePcs: RTCPeerConnection[] }).__e2eIcePcs;
    const pc = pcs[pcs.length - 1];
    Object.defineProperty(pc, "iceConnectionState", {
      configurable: true,
      get: () => "failed",
    });
    pc.dispatchEvent(new Event("iceconnectionstatechange"));
  });
}

/** Intercept every `/ndi/whep/*` request (this CI runner has no NDI SDK, so
 * the real server always answers 503/204 — see the file header). POST (the
 * WHEP offer) is answered with a genuine SDP answer generated by an
 * ephemeral in-page `RTCPeerConnection` (a REAL Chrome-negotiated answer, so
 * the client's `set_remote_description` genuinely succeeds); any other
 * method (the session-teardown DELETE) is answered 204, matching the real
 * server's own idempotent-DELETE behavior (ndi_whep.rs). */
async function installFakeWhepServer(page: Page): Promise<void> {
  let resourceCounter = 0;
  await page.route(
    (url) => url.pathname.startsWith("/ndi/whep/"),
    async (route: Route) => {
      if (route.request().method() !== "POST") {
        await route.fulfill({ status: 204 });
        return;
      }
      const offerSdp = route.request().postData() ?? "";
      const answerSdp = await page.evaluate(async (offer) => {
        const serverPc = new RTCPeerConnection();
        await serverPc.setRemoteDescription({ type: "offer", sdp: offer });
        const answer = await serverPc.createAnswer();
        await serverPc.setLocalDescription(answer);
        const sdp = serverPc.localDescription?.sdp ?? "";
        serverPc.close();
        return sdp;
      }, offerSdp);
      resourceCounter += 1;
      await route.fulfill({
        status: 201,
        headers: {
          Location: `/ndi/whep/e2e-fake-resource-${resourceCounter}`,
          "Content-Type": "application/sdp",
        },
        body: answerSdp,
      });
    },
  );
}

async function openStageWithNdiVideo(page: Page, label: string): Promise<string> {
  await page.request.post(
    new URL("/integrations/video-sources/deactivate", baseURL).toString(),
    { failOnStatusCode: false },
  );
  await page.request.post(new URL("/stage/layout", baseURL).toString(), {
    data: { code: "ndi-fullscreen" },
  });
  const created = await page.request.post(
    new URL("/integrations/video-sources", baseURL).toString(),
    { data: { label, ndiName: `BOGUS-${label}` } },
  );
  const source = await created.json();
  await page.request.post(
    new URL(`/integrations/video-sources/${source.id}/activate`, baseURL).toString(),
    { failOnStatusCode: false },
  );

  await page.goto(new URL("/stage", baseURL).toString());
  await page.waitForSelector('body[data-wasm-ready="true"]', { timeout: 30_000 });
  await page.waitForSelector('[data-role="ndi-video"]', { timeout: 15_000 });

  return source.id as string;
}

async function deactivateAndDelete(page: Page, sourceId: string): Promise<void> {
  await page.request.post(
    new URL("/integrations/video-sources/deactivate", baseURL).toString(),
    { failOnStatusCode: false },
  );
  await page.request.delete(
    new URL(`/integrations/video-sources/${sourceId}`, baseURL).toString(),
    { failOnStatusCode: false },
  );
}

test("install_pagehide_teardown does not leak a window pagehide listener across WHEP reconnects (#670)", async ({
  page,
}) => {
  const consoleMessages: string[] = [];
  attachConsoleErrorCollector(page, consoleMessages);

  await installFakeWhepServer(page);
  await installIceAndPagehideInstrumentation(page);

  const sourceId = await openStageWithNdiVideo(page, "PagehideLeak");

  try {
    // First connect: exactly one pagehide listener installed.
    await expect
      .poll(() => pagehideNet(page), {
        timeout: 15_000,
        message: "first WHEP connect never installed the pagehide listener",
      })
      .toBe(1);

    for (let cycle = 0; cycle < 3; cycle += 1) {
      await forceIceFailure(page);

      // The reconnect loop tears down the old session (disposing its
      // pagehide handle, #670) then re-POSTs WHEP for a new one, which
      // installs a fresh handle. Net count must return to exactly 1 —
      // NEVER 2+ — after every cycle: before the #670 fix this climbed by
      // one every reconnect (2, 3, 4, ...) because the old handle was
      // never disposed.
      await expect
        .poll(() => pagehideNet(page), {
          timeout: 15_000,
          message: `cycle ${cycle}: pagehide listener net count is not 1 after reconnect (leak)`,
        })
        .toBe(1);
    }

    const unexpected = consoleMessages.filter(
      (m) => !ALLOWED_CONSOLE_NOISE.some((re) => re.test(m)),
    );
    expect(unexpected).toEqual([]);
  } finally {
    await deactivateAndDelete(page, sourceId);
  }

  // Page-level teardown (on_cleanup) must also dispose the LAST session's
  // pagehide handle — mirrors the #637 test's own unmount assertion.
  await expect
    .poll(() => pagehideNet(page), {
      timeout: 10_000,
      message: "pagehide listener not removed on unmount (leak)",
    })
    .toBe(0);
});
